version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; alembic upgrade head; uvicorn src.api:app --host 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 5001:8000
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=test
      - DB_PASSWORD=test
      - DB_DATABASE=fulexpro
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=fulexpro

volumes:
  postgres_data:
